secret_path         = "path to /secret.ini"
region              = "us-east-1"
private_key_path    = "path to .pem"
ec2_avail_zone      = "us-east-1a"
author_name         = "author name"
main_dir            = "path to main folder"
