server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_management
    username: user
    password: 123456789Aa&
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: 'create-drop'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  file:
    name: ${user.home}/.school_management/runtime.log